create table public.users (
  id bigint generated by default as identity not null,
  name character varying null,
  email character varying not null,
  password character varying null,
  created_at timestamp with time zone not null default now(),
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;

create table public.teams (
  id bigint generated by default as identity not null,
  name character varying not null,
  description character varying null,
  created_at timestamp with time zone not null default now(),
  constraint teams_pkey primary key (id)
) TABLESPACE pg_default;

create table public.team_members (
  team_id bigint not null,
  user_id bigint not null,
  constraint team_members_pkey primary key (team_id, user_id),
  constraint team_members_team_id_fkey foreign KEY (team_id) references teams (id) on update CASCADE on delete CASCADE,
  constraint team_members_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.projects (
  id bigint generated by default as identity not null,
  name character varying null,
  status character varying not null,
  deadline date not null,
  budget character varying not null,
  team_member bigint not null,
  description character varying null,
  created_at timestamp with time zone not null default now(),
  constraint projects_pkey primary key (id),
  constraint projects_team_member_fkey foreign KEY (team_member) references users (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;